---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - htop
          - python3-pip
          - make
          - flameshot
          - mlocate
          - terminator
          - xpad

    - name: Installing Zoom
      become: true
      apt:
        deb: "https://zoom.us/client/latest/zoom_amd64.deb"
        install_recommends: yes
        state: present

    - block:
      - name: Install Virtualbox Oracle Key
        become: true
        apt_key:
          url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
          state: present
      - name: Add Virtualbox Oracle repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
          state: present
          filename: virtualbox
      - name: Install Oracle Virtualbox
        become: true
        apt:
          name: virtualbox-6.1

    - block: 
      - name: Install Vagrant Key
        become: true
        apt_key:
          url: 'https://apt.releases.hashicorp.com/gpg'
          state: present
      - name: Install Vagrant Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
          state: present
          filename: vagrant
      - name: Install Vagrant
        become: true
        apt:
          name: vagrant

          
    - block:
      - name: Install Microsoft Key
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      - name: Add Microsoft Teams Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
          state: present
          filename: teams
      - name: Install Microsoft Teams
        become: true
        apt:
          name: teams
        
    - block: 
      - name: Install Google Chrome Key
        shell: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - name: Install Google Chrome Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
          state: present
          filename: brave
      - name: Install Google Chrome
        become: true
        apt:
          name: google-chrome-stable

    - block: 
      - name: Install Brave Key
        become: true
        apt_key:
          url: 'https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
          state: present
      - name: Install Brave Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
          state: present
          filename: brave
      - name: Install Brave Browser
        become: true
        apt:
          name: brave-browser
